[supervisord]
nodaemon=true

[program:maoyan_spider]
directory=/usr/src/app/maoyan_spider
command=python -u maoyan_spider.py
autorestart=true
startretries=50
stdout_logfile=/logs/maoyan_spider.log
redirect_stderr=true
